<a href="https://colab.research.google.com/github/Heashalla/FYP/blob/main/01_data_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NHANES Cardiometabolic-Risk Project

## Notebook 01: Raw Data Extraction

This notebook imports and inspects the original NHANES XPT files for the 2013–2014, 2015–2016 and 2017–2018 survey cycles.

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
from pathlib import Path

project_folder = Path("/content/drive/MyDrive/NHANES_Project")
zip_file = project_folder / "NHANES_raw_data.zip"

print("Project folder:", project_folder)
print("Project folder exists:", project_folder.exists())
print()
print("ZIP file:", zip_file)
print("ZIP file exists:", zip_file.exists())

if zip_file.exists():
    size_mb = zip_file.stat().st_size / (1024 * 1024)
    print(f"ZIP file size: {size_mb:.2f} MB")
    print("\nStatus: ZIP file located successfully.")
else:
    print("\nStatus: ZIP file was not found.")

Project folder: /content/drive/MyDrive/NHANES_Project
Project folder exists: True

ZIP file: /content/drive/MyDrive/NHANES_Project/NHANES_raw_data.zip
ZIP file exists: True
ZIP file size: 10.65 MB

Status: ZIP file located successfully.

In [4]:
import zipfile
from pathlib import Path

with zipfile.ZipFile(zip_file, "r") as zip_archive:
    all_entries = zip_archive.namelist()

# Exclude folder entries
files_inside = [
    entry for entry in all_entries
    if not entry.endswith("/")
]

# Select XPT files regardless of upper/lowercase extension
xpt_files = [
    entry for entry in files_inside
    if Path(entry).suffix.lower() == ".xpt"
]

other_files = [
    entry for entry in files_inside
    if Path(entry).suffix.lower() != ".xpt"
]

print("ZIP inspection completed")
print("-" * 60)
print("Total files found:", len(files_inside))
print("XPT files found:", len(xpt_files))
print("Other files found:", len(other_files))

print("\nXPT FILES")
print("-" * 60)

for number, file_name in enumerate(sorted(xpt_files), start=1):
    print(f"{number:02d}. {file_name}")

if other_files:
    print("\nOTHER FILES")
    print("-" * 60)

    for file_name in sorted(other_files):
        print(file_name)

print("\nVALIDATION")
print("-" * 60)

if len(xpt_files) == 33:
    print("Status: All 33 expected XPT files were found.")
else:
    print(f"Status: Expected 33 XPT files, but found {len(xpt_files)}.")

ZIP inspection completed
------------------------------------------------------------
Total files found: 33
XPT files found: 33
Other files found: 0

XPT FILES
------------------------------------------------------------
01. raw_data/2013_2014/BMX_H.XPT
02. raw_data/2013_2014/BPQ_H.XPT
03. raw_data/2013_2014/BPX_H.XPT
04. raw_data/2013_2014/DEMO_H.XPT
05. raw_data/2013_2014/DIQ_H.XPT
06. raw_data/2013_2014/DR1TOT_H.XPT
07. raw_data/2013_2014/GLU_H.xpt
08. raw_data/2013_2014/HDL_H.XPT
09. raw_data/2013_2014/INS_H.xpt
10. raw_data/2013_2014/PAQ_H.XPT
11. raw_data/2013_2014/TRIGLY_H.XPT
12. raw_data/2015_2016/BMX_I.XPT
13. raw_data/2015_2016/BPQ_I.XPT
14. raw_data/2015_2016/BPX_I.XPT
15. raw_data/2015_2016/DEMO_I.XPT
16. raw_data/2015_2016/DIQ_I.XPT
17. raw_data/2015_2016/DR1TOT_I.XPT
18. raw_data/2015_2016/GLU_I.xpt
19. raw_data/2015_2016/HDL_I.XPT
20. raw_data/2015_2016/INS_I.xpt
21. raw_data/2015_2016/PAQ_I.XPT
22. raw_data/2015_2016/TRIGLY_I.XPT
23. raw_data/2017_2018/BMX_J.XPT
24. raw_data/2017_2018/BPQ_J.XPT
25. raw_data/2017_2018/BPX_J.XPT
26. raw_data/2017_2018/DEMO_J.XPT
27. raw_data/2017_2018/DIQ_J.XPT
28. raw_data/2017_2018/DR1TOT_J.XPT
29. raw_data/2017_2018/GLU_J.xpt
30. raw_data/2017_2018/HDL_J.XPT
31. raw_data/2017_2018/INS_J.xpt
32. raw_data/2017_2018/PAQ_J.XPT
33. raw_data/2017_2018/TRIGLY_J.XPT

VALIDATION
------------------------------------------------------------
Status: All 33 expected XPT files were found.

In [6]:
expected_files = {
    "2013_2014": {
        "BMX_H.XPT", "BPQ_H.XPT", "BPX_H.XPT", "DEMO_H.XPT",
        "DIQ_H.XPT", "DR1TOT_H.XPT", "GLU_H.XPT", "HDL_H.XPT",
        "PAQ_H.XPT", "TRIGLY_H.XPT","INS_H.XPT"
    },
    "2015_2016": {
        "BMX_I.XPT", "BPQ_I.XPT", "BPX_I.XPT", "DEMO_I.XPT",
        "DIQ_I.XPT", "DR1TOT_I.XPT", "GLU_I.XPT", "HDL_I.XPT",
        "PAQ_I.XPT", "TRIGLY_I.XPT","INS_I.XPT"
    },
    "2017_2018": {
        "BMX_J.XPT", "BPQ_J.XPT", "BPX_J.XPT", "DEMO_J.XPT",
        "DIQ_J.XPT", "DR1TOT_J.XPT", "GLU_J.XPT", "HDL_J.XPT",
        "PAQ_J.XPT", "TRIGLY_J.XPT", "INS_J.XPT"
    }
}

all_cycles_valid = True

for cycle, expected in expected_files.items():

    found = {
        Path(file_name).name.upper()
        for file_name in xpt_files
        if cycle in file_name
    }

    missing = expected - found
    unexpected = found - expected

    print(f"\nCycle: {cycle}")
    print("-" * 40)
    print("Expected files:", len(expected))
    print("Files found:", len(found))

    if not missing and not unexpected:
        print("Status: Complete")
    else:
        all_cycles_valid = False
        print("Status: Check required")

        if missing:
            print("Missing files:", sorted(missing))

        if unexpected:
            print("Unexpected files:", sorted(unexpected))

print("\nOVERALL VALIDATION")
print("-" * 40)

if all_cycles_valid:
    print("Status: All three survey cycles are complete.")
    print("The ZIP file is ready for extraction.")
else:
    print("Status: One or more cycles require correction.")

Cycle: 2013_2014
----------------------------------------
Expected files: 11
Files found: 11
Status: Complete

Cycle: 2015_2016
----------------------------------------
Expected files: 11
Files found: 11
Status: Complete

Cycle: 2017_2018
----------------------------------------
Expected files: 11
Files found: 11
Status: Complete

OVERALL VALIDATION
----------------------------------------
Status: All three survey cycles are complete.
The ZIP file is ready for extraction.

In [8]:
import zipfile
from pathlib import Path

extraction_folder = Path("/content/NHANES_Project")
extraction_folder.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(zip_file, "r") as zip_archive:
    zip_archive.extractall(extraction_folder)

raw_data_folder = extraction_folder / "raw_data"

extracted_xpt_files = sorted([
    file_path
    for file_path in raw_data_folder.rglob("*")
    if file_path.is_file() and file_path.suffix.lower() == ".xpt"
])

print("Extraction completed")
print("-" * 60)
print("Extraction folder:", extraction_folder)
print("Raw-data folder exists:", raw_data_folder.exists())
print("XPT files extracted:", len(extracted_xpt_files))

print("\nEXTRACTED FILES")
print("-" * 60)

for number, file_path in enumerate(extracted_xpt_files, start=1):
    relative_path = file_path.relative_to(extraction_folder)
    print(f"{number:02d}. {relative_path}")

print("\nVALIDATION")
print("-" * 60)

if len(extracted_xpt_files) == 33:
    print("Status: All 33 XPT files were extracted successfully.")
else:
    print(f"Status: Expected 33 files, but extracted {len(extracted_xpt_files)}.")

Extraction completed
------------------------------------------------------------
Extraction folder: /content/NHANES_Project
Raw-data folder exists: True
XPT files extracted: 33

EXTRACTED FILES
------------------------------------------------------------
01. raw_data/2013_2014/BMX_H.XPT
02. raw_data/2013_2014/BPQ_H.XPT
03. raw_data/2013_2014/BPX_H.XPT
04. raw_data/2013_2014/DEMO_H.XPT
05. raw_data/2013_2014/DIQ_H.XPT
06. raw_data/2013_2014/DR1TOT_H.XPT
07. raw_data/2013_2014/GLU_H.xpt
08. raw_data/2013_2014/HDL_H.XPT
09. raw_data/2013_2014/INS_H.xpt
10. raw_data/2013_2014/PAQ_H.XPT
11. raw_data/2013_2014/TRIGLY_H.XPT
12. raw_data/2015_2016/BMX_I.XPT
13. raw_data/2015_2016/BPQ_I.XPT
14. raw_data/2015_2016/BPX_I.XPT
15. raw_data/2015_2016/DEMO_I.XPT
16. raw_data/2015_2016/DIQ_I.XPT
17. raw_data/2015_2016/DR1TOT_I.XPT
18. raw_data/2015_2016/GLU_I.xpt
19. raw_data/2015_2016/HDL_I.XPT
20. raw_data/2015_2016/INS_I.xpt
21. raw_data/2015_2016/PAQ_I.XPT
22. raw_data/2015_2016/TRIGLY_I.XPT
23. raw_data/2017_2018/BMX_J.XPT
24. raw_data/2017_2018/BPQ_J.XPT
25. raw_data/2017_2018/BPX_J.XPT
26. raw_data/2017_2018/DEMO_J.XPT
27. raw_data/2017_2018/DIQ_J.XPT
28. raw_data/2017_2018/DR1TOT_J.XPT
29. raw_data/2017_2018/GLU_J.xpt
30. raw_data/2017_2018/HDL_J.XPT
31. raw_data/2017_2018/INS_J.xpt
32. raw_data/2017_2018/PAQ_J.XPT
33. raw_data/2017_2018/TRIGLY_J.XPT

VALIDATION
------------------------------------------------------------
Status: All 33 XPT files were extracted successfully.

In [9]:
import pandas as pd
from IPython.display import display

demo_h_path = raw_data_folder / "2013_2014" / "DEMO_H.XPT"

print("File:", demo_h_path.name)
print("File exists:", demo_h_path.exists())

demo_h = pd.read_sas(
    demo_h_path,
    format="xport",
    encoding="latin-1"
)

print("\nDATASET SUMMARY")
print("-" * 60)
print("Survey cycle: 2013–2014")
print("Number of rows:", demo_h.shape[0])
print("Number of columns:", demo_h.shape[1])
print("Duplicate SEQN values:", demo_h["SEQN"].duplicated().sum())
print("Total missing cells:", demo_h.isna().sum().sum())

print("\nCOLUMN NAMES")
print("-" * 60)
print(demo_h.columns.tolist())

print("\nFIRST FIVE PARTICIPANTS")
print("-" * 60)
display(demo_h.head())

File: DEMO_H.XPT
File exists: True

DATASET SUMMARY
------------------------------------------------------------
Survey cycle: 2013–2014
Number of rows: 10175
Number of columns: 47
Duplicate SEQN values: 0
Total missing cells: 82092

COLUMN NAMES
------------------------------------------------------------
['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN', 'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'RIDEXAGM', 'DMQMILIZ', 'DMQADFC', 'DMDBORN4', 'DMDCITZN', 'DMDYRSUS', 'DMDEDUC3', 'DMDEDUC2', 'DMDMARTL', 'RIDEXPRG', 'SIALANG', 'SIAPROXY', 'SIAINTRP', 'FIALANG', 'FIAPROXY', 'FIAINTRP', 'MIALANG', 'MIAPROXY', 'MIAINTRP', 'AIALANGA', 'DMDHHSIZ', 'DMDFMSIZ', 'DMDHHSZA', 'DMDHHSZB', 'DMDHHSZE', 'DMDHRGND', 'DMDHRAGE', 'DMDHRBR4', 'DMDHREDU', 'DMDHRMAR', 'DMDHSEDU', 'WTINT2YR', 'WTMEC2YR', 'SDMVPSU', 'SDMVSTRA', 'INDHHIN2', 'INDFMIN2', 'INDFMPIR']

FIRST FIVE PARTICIPANTS
------------------------------------------------------------

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDU,DMDHRMAR,DMDHSEDU,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
0,73557.0,8.0,2.0,1.0,69.0,NaN,4.0,4.0,1.0,NaN,...,3.0,4.0,NaN,13281.237386,13481.042095,1.0,112.0,4.0,4.0,0.84
1,73558.0,8.0,2.0,1.0,54.0,NaN,3.0,3.0,1.0,NaN,...,3.0,1.0,1.0,23682.057386,24471.769625,1.0,108.0,7.0,7.0,1.78
2,73559.0,8.0,2.0,1.0,72.0,NaN,3.0,3.0,2.0,NaN,...,4.0,1.0,3.0,57214.803319,57193.285376,1.0,109.0,10.0,10.0,4.51
3,73560.0,8.0,2.0,1.0,9.0,NaN,3.0,3.0,1.0,119.0,...,3.0,1.0,4.0,55201.178592,55766.512438,2.0,109.0,9.0,9.0,2.52
4,73561.0,8.0,2.0,2.0,73.0,NaN,3.0,3.0,1.0,NaN,...,5.0,1.0,5.0,63709.667069,65541.871229,2.0,116.0,15.0,15.0,5.00

In [10]:
import pandas as pd
from pathlib import Path
from openpyxl.styles import Font, PatternFill, Alignment

# Permanent Excel output location in Google Drive
excel_root = project_folder / "raw_excel"
excel_root.mkdir(parents=True, exist_ok=True)

extraction_summary = []

print("Starting XPT-to-Excel conversion")
print("=" * 70)

for number, xpt_path in enumerate(extracted_xpt_files, start=1):

    cycle = xpt_path.parent.name

    cycle_output_folder = excel_root / cycle
    cycle_output_folder.mkdir(parents=True, exist_ok=True)

    excel_name = f"{xpt_path.stem.upper()}.xlsx"
    excel_path = cycle_output_folder / excel_name

    try:
        # Read the original XPT file
        dataframe = pd.read_sas(
            xpt_path,
            format="xport",
            encoding="latin-1"
        )

        # Display participant IDs as whole numbers in Excel
        if "SEQN" in dataframe.columns:
            dataframe["SEQN"] = pd.to_numeric(
                dataframe["SEQN"],
                errors="coerce"
            ).astype("Int64")

        duplicate_seqn = (
            int(dataframe["SEQN"].duplicated().sum())
            if "SEQN" in dataframe.columns
            else None
        )

        # Export to Excel
        with pd.ExcelWriter(
            excel_path,
            engine="openpyxl"
        ) as writer:

            dataframe.to_excel(
                writer,
                sheet_name="Raw_Data",
                index=False
            )

            worksheet = writer.book["Raw_Data"]

            # Keep the column names visible when scrolling
            worksheet.freeze_panes = "A2"

            # Add filters to the complete table
            worksheet.auto_filter.ref = worksheet.dimensions

            # Format the header row
            header_fill = PatternFill(
                fill_type="solid",
                fgColor="1F4E78"
            )

            for cell in worksheet[1]:
                cell.font = Font(
                    bold=True,
                    color="FFFFFF"
                )
                cell.fill = header_fill
                cell.alignment = Alignment(
                    horizontal="center"
                )

        extraction_summary.append({
            "Survey_Cycle": cycle,
            "XPT_File": xpt_path.name,
            "Excel_File": excel_name,
            "Rows": dataframe.shape[0],
            "Columns": dataframe.shape[1],
            "Duplicate_SEQN": duplicate_seqn,
            "Missing_Cells": int(dataframe.isna().sum().sum()),
            "Status": "Successfully converted"
        })

        print(
            f"{number:02d}/30 | {cycle} | "
            f"{xpt_path.name} → {excel_name} | "
            f"{dataframe.shape[0]:,} rows × "
            f"{dataframe.shape[1]} columns"
        )

    except Exception as error:

        extraction_summary.append({
            "Survey_Cycle": cycle,
            "XPT_File": xpt_path.name,
            "Excel_File": excel_name,
            "Rows": None,
            "Columns": None,
            "Duplicate_SEQN": None,
            "Missing_Cells": None,
            "Status": f"Failed: {error}"
        })

        print(
            f"{number:02d}/30 | FAILED | "
            f"{xpt_path.name} | {error}"
        )

print("=" * 70)
print("Conversion process completed.")

Starting XPT-to-Excel conversion
======================================================================
01/30 | 2013_2014 | BMX_H.XPT → BMX_H.xlsx | 9,813 rows × 26 columns
02/30 | 2013_2014 | BPQ_H.XPT → BPQ_H.xlsx | 6,464 rows × 14 columns
03/30 | 2013_2014 | BPX_H.XPT → BPX_H.xlsx | 9,813 rows × 23 columns
04/30 | 2013_2014 | DEMO_H.XPT → DEMO_H.xlsx | 10,175 rows × 47 columns
05/30 | 2013_2014 | DIQ_H.XPT → DIQ_H.xlsx | 9,770 rows × 54 columns
06/30 | 2013_2014 | DR1TOT_H.XPT → DR1TOT_H.xlsx | 9,813 rows × 168 columns
07/30 | 2013_2014 | GLU_H.xpt → GLU_H.xlsx | 3,329 rows × 6 columns
08/30 | 2013_2014 | HDL_H.XPT → HDL_H.xlsx | 8,291 rows × 3 columns
09/30 | 2013_2014 | INS_H.xpt → INS_H.xlsx | 3,329 rows × 6 columns
10/30 | 2013_2014 | PAQ_H.XPT → PAQ_H.xlsx | 9,484 rows × 96 columns
11/30 | 2013_2014 | TRIGLY_H.XPT → TRIGLY_H.xlsx | 3,329 rows × 6 columns
12/30 | 2015_2016 | BMX_I.XPT → BMX_I.xlsx | 9,544 rows × 26 columns
13/30 | 2015_2016 | BPQ_I.XPT → BPQ_I.xlsx | 6,327 rows × 11 columns
14/30 | 2015_2016 | BPX_I.XPT → BPX_I.xlsx | 9,544 rows × 21 columns
15/30 | 2015_2016 | DEMO_I.XPT → DEMO_I.xlsx | 9,971 rows × 47 columns
16/30 | 2015_2016 | DIQ_I.XPT → DIQ_I.xlsx | 9,575 rows × 54 columns
17/30 | 2015_2016 | DR1TOT_I.XPT → DR1TOT_I.xlsx | 9,544 rows × 168 columns
18/30 | 2015_2016 | GLU_I.xpt → GLU_I.xlsx | 3,191 rows × 4 columns
19/30 | 2015_2016 | HDL_I.XPT → HDL_I.xlsx | 8,021 rows × 3 columns
20/30 | 2015_2016 | INS_I.xpt → INS_I.xlsx | 3,191 rows × 7 columns
21/30 | 2015_2016 | PAQ_I.XPT → PAQ_I.xlsx | 9,255 rows × 94 columns
22/30 | 2015_2016 | TRIGLY_I.XPT → TRIGLY_I.xlsx | 3,191 rows × 6 columns
23/30 | 2017_2018 | BMX_J.XPT → BMX_J.xlsx | 8,704 rows × 21 columns
24/30 | 2017_2018 | BPQ_J.XPT → BPQ_J.xlsx | 6,161 rows × 11 columns
25/30 | 2017_2018 | BPX_J.XPT → BPX_J.xlsx | 8,704 rows × 21 columns
26/30 | 2017_2018 | DEMO_J.XPT → DEMO_J.xlsx | 9,254 rows × 46 columns
27/30 | 2017_2018 | DIQ_J.XPT → DIQ_J.xlsx | 8,897 rows × 54 columns
28/30 | 2017_2018 | DR1TOT_J.XPT → DR1TOT_J.xlsx | 8,704 rows × 168 columns
29/30 | 2017_2018 | GLU_J.xpt → GLU_J.xlsx | 3,036 rows × 4 columns
30/30 | 2017_2018 | HDL_J.XPT → HDL_J.xlsx | 7,435 rows × 3 columns
31/30 | 2017_2018 | INS_J.xpt → INS_J.xlsx | 3,036 rows × 5 columns
32/30 | 2017_2018 | PAQ_J.XPT → PAQ_J.xlsx | 5,856 rows × 17 columns
33/30 | 2017_2018 | TRIGLY_J.XPT → TRIGLY_J.xlsx | 3,036 rows × 10 columns
======================================================================
Conversion process completed.

In [11]:
summary_dataframe = pd.DataFrame(extraction_summary)

reports_folder = project_folder / "reports"
reports_folder.mkdir(parents=True, exist_ok=True)

summary_file = reports_folder / "extraction_summary.xlsx"

summary_dataframe.to_excel(
    summary_file,
    sheet_name="Extraction_Summary",
    index=False
)

successful_files = (
    summary_dataframe["Status"] == "Successfully converted"
).sum()

failed_files = len(summary_dataframe) - successful_files

print("EXTRACTION SUMMARY")
print("-" * 70)
print("Files processed:", len(summary_dataframe))
print("Successfully converted:", successful_files)
print("Failed conversions:", failed_files)
print("Excel output folder:", excel_root)
print("Summary report:", summary_file)

display(summary_dataframe)

EXTRACTION SUMMARY
----------------------------------------------------------------------
Files processed: 33
Successfully converted: 33
Failed conversions: 0
Excel output folder: /content/drive/MyDrive/NHANES_Project/raw_excel
Summary report: /content/drive/MyDrive/NHANES_Project/reports/extraction_summary.xlsx

,Survey_Cycle,XPT_File,Excel_File,Rows,Columns,Duplicate_SEQN,Missing_Cells,Status
0,2013_2014,BMX_H.XPT,BMX_H.xlsx,9813,26,0,143166,Successfully converted
1,2013_2014,BPQ_H.XPT,BPQ_H.xlsx,6464,14,0,33153,Successfully converted
2,2013_2014,BPX_H.XPT,BPX_H.xlsx,9813,23,0,78847,Successfully converted
3,2013_2014,DEMO_H.XPT,DEMO_H.xlsx,10175,47,0,82092,Successfully converted
4,2013_2014,DIQ_H.XPT,DIQ_H.xlsx,9770,54,0,453621,Successfully converted
5,2013_2014,DR1TOT_H.XPT,DR1TOT_H.xlsx,9813,168,0,704978,Successfully converted
6,2013_2014,GLU_H.xpt,GLU_H.xlsx,3329,6,0,390,Successfully converted
7,2013_2014,HDL_H.XPT,HDL_H.xlsx,8291,3,0,1334,Successfully converted
8,2013_2014,INS_H.xpt,INS_H.xlsx,3329,6,0,548,Successfully converted
9,2013_2014,PAQ_H.XPT,PAQ_H.xlsx,9484,96,0,775493,Successfully converted
10,2013_2014,TRIGLY_H.XPT,TRIGLY_H.xlsx,3329,6,0,814,Successfully converted
11,2015_2016,BMX_I.XPT,BMX_I.xlsx,9544,26,0,139669,Successfully converted
12,2015_2016,BPQ_I.XPT,BPQ_I.xlsx,6327,11,0,27329,Successfully converted
13,2015_2016,BPX_I.XPT,BPX_I.xlsx,9544,21,0,76311,Successfully converted
14,2015_2016,DEMO_I.XPT,DEMO_I.xlsx,9971,47,0,82430,Successfully converted
15,2015_2016,DIQ_I.XPT,DIQ_I.xlsx,9575,54,0,441440,Successfully converted
16,2015_2016,DR1TOT_I.XPT,DR1TOT_I.xlsx,9544,168,0,684306,Successfully converted
17,2015_2016,GLU_I.xpt,GLU_I.xlsx,3191,4,0,438,Successfully converted
18,2015_2016,HDL_I.XPT,HDL_I.xlsx,8021,3,0,1530,Successfully converted
19,2015_2016,INS_I.xpt,INS_I.xlsx,3191,7,0,922,Successfully converted
20,2015_2016,PAQ_I.XPT,PAQ_I.xlsx,9255,94,0,747153,Successfully converted
21,2015_2016,TRIGLY_I.XPT,TRIGLY_I.xlsx,3191,6,0,1920,Successfully converted
22,2017_2018,BMX_J.XPT,BMX_J.xlsx,8704,21,0,100717,Successfully converted
23,2017_2018,BPQ_J.XPT,BPQ_J.xlsx,6161,11,0,26003,Successfully converted
24,2017_2018,BPX_J.XPT,BPX_J.xlsx,8704,21,0,70095,Successfully converted
25,2017_2018,DEMO_J.XPT,DEMO_J.xlsx,9254,46,0,77531,Successfully converted
26,2017_2018,DIQ_J.XPT,DIQ_J.xlsx,8897,54,0,406660,Successfully converted
27,2017_2018,DR1TOT_J.XPT,DR1TOT_J.xlsx,8704,168,0,637156,Successfully converted
28,2017_2018,GLU_J.xpt,GLU_J.xlsx,3036,4,0,290,Successfully converted
29,2017_2018,HDL_J.XPT,HDL_J.xlsx,7435,3,0,1394,Successfully converted
30,2017_2018,INS_J.xpt,INS_J.xlsx,3036,5,0,633,Successfully converted
31,2017_2018,PAQ_J.XPT,PAQ_J.xlsx,5856,17,0,40592,Successfully converted
32,2017_2018,TRIGLY_J.XPT,TRIGLY_J.xlsx,3036,10,0,1734,Successfully converted

In [12]:
import pandas as pd
from IPython.display import display

research_variable_rows = [
    (
        "SEQN", "All datasets", "Identifier",
        "Unique NHANES participant identification number",
        "Participant ID", "Merge key",
        "Links participant records within each survey cycle"
    ),
    (
        "RIDAGEYR", "DEMO", "Demographic",
        "Participant age at screening",
        "Years", "Predictor and eligibility",
        "Included in prediction models; final adult age range to be confirmed"
    ),
    (
        "RIAGENDR", "DEMO", "Demographic",
        "Participant sex as recorded by NHANES",
        "1 = Male; 2 = Female", "Predictor and score reference",
        "Model predictor; used for sex-specific standardisation if adopted"
    ),
    (
        "RIDEXPRG", "DEMO", "Eligibility",
        "Pregnancy status at examination",
        "1 = Positive; 2 = Negative; 3 = Cannot ascertain",
        "Eligibility audit",
        "Assess pregnancy exclusion; missing or unknown is not automatically negative"
    ),
    (
        "SDMVPSU", "DEMO", "Survey design",
        "Masked primary sampling unit",
        "NHANES survey-design code", "Survey design",
        "Retained for survey-design-aware analysis"
    ),
    (
        "SDMVSTRA", "DEMO", "Survey design",
        "Masked variance stratum",
        "NHANES survey-design code", "Survey design",
        "Retained for survey-design-aware analysis"
    ),
    (
        "WTSAF2YR", "GLU / TRIGLY / INS", "Survey weight",
        "Two-year fasting-subsample weight",
        "Survey weight", "Analysis weight",
        "Compare across laboratory files before retaining one; pooled weighting requires a specified analysis plan"
    ),
    (
        "PHAFSTHR", "INS; also GLU where available", "Fasting audit",
        "Reported fasting duration: hours component",
        "Hours", "Eligibility and quality audit",
        "Combine with PHAFSTMN to assess fasting duration"
    ),
    (
        "PHAFSTMN", "INS; also GLU where available", "Fasting audit",
        "Reported fasting duration: minutes component",
        "Minutes", "Eligibility and quality audit",
        "Combine with PHAFSTHR; apply the agreed fasting eligibility rule"
    ),
    (
        "BMXHT", "BMX", "Anthropometric",
        "Standing height",
        "Centimetres", "Index calculation input",
        "Used to calculate WHtR, BRI and ABSI and to check BMI"
    ),
    (
        "BMXWT", "BMX", "Anthropometric",
        "Measured body weight",
        "Kilograms", "Index calculation input",
        "Used to calculate or check BMI and audit body measurements"
    ),
    (
        "BMXWAIST", "BMX", "Anthropometric",
        "Measured waist circumference",
        "Centimetres", "Index calculation input",
        "Used to calculate WHtR, BRI and ABSI; excluded from the proposed outcome"
    ),
    (
        "BMXBMI", "BMX", "Anthropometric",
        "NHANES body mass index",
        "kg/m²", "Predictor",
        "Used in the BMI comparison model"
    ),
    (
        "BPXSY1–BPXSY4", "BPX", "Blood pressure",
        "Repeated systolic blood-pressure measurements",
        "mmHg", "Outcome construction input",
        "Eligible readings are averaged according to the final BP-quality protocol"
    ),
    (
        "BPXDI1–BPXDI4", "BPX", "Blood pressure",
        "Repeated diastolic blood-pressure measurements",
        "mmHg", "Outcome construction input",
        "Eligible readings are averaged according to the final BP-quality protocol"
    ),
    (
        "BPQ020", "BPQ", "Hypertension history",
        "Ever told by a health professional that participant had high blood pressure",
        "Use cycle-specific codebook", "History and sensitivity audit",
        "Describes hypertension history; not directly added to the continuous score"
    ),
    (
        "BPQ040A", "BPQ", "Hypertension treatment",
        "Ever advised to take prescribed medicine for high blood pressure",
        "Use cycle-specific codebook", "Treatment-history audit",
        "Records treatment advice; does not alone establish current medication use"
    ),
    (
        "BPQ050A", "BPQ", "Hypertension treatment",
        "Currently taking prescribed medicine for high blood pressure",
        "Use cycle-specific codebook and questionnaire routing",
        "Medication audit",
        "Assess current treatment; final treatment-handling policy remains to be specified"
    ),
    (
        "LBXGLU", "GLU", "Glycaemia",
        "Fasting plasma glucose",
        "mg/dL", "Proposed outcome component",
        "Continuous glucose input; transformation and reference standardisation must follow the final protocol"
    ),
    (
        "LBXIN", "INS", "Insulin",
        "Measured serum insulin concentration",
        "µU/mL", "Proposed outcome component",
        "Continuous insulin input; distinct from insulin medication use"
    ),
    (
        "LBDINSI", "INS", "Insulin",
        "Serum insulin concentration in SI units",
        "pmol/L", "Supporting laboratory variable",
        "Alternative units for insulin; not a separate score component"
    ),
    (
        "LBDINLC", "INS", "Laboratory quality",
        "Insulin detection-limit comment code",
        "0 = At or above detection limit; 1 = Below detection limit",
        "Laboratory quality audit",
        "Identify results below the detection limit and document their handling"
    ),
    (
        "DIQ050", "DIQ", "Diabetes treatment",
        "Currently taking insulin",
        "Use cycle-specific codebook and questionnaire routing",
        "Medication audit",
        "Identifies insulin treatment; does not substitute for LBXIN"
    ),
    (
        "DIQ070", "DIQ", "Diabetes treatment",
        "Currently taking diabetic pills to lower blood sugar",
        "Use cycle-specific codebook and questionnaire routing",
        "Medication audit",
        "Assess glucose-lowering treatment under the final medication policy"
    ),
    (
        "LBXTR", "TRIGLY", "Lipids",
        "Fasting triglyceride concentration",
        "mg/dL", "Proposed outcome component",
        "Continuous triglyceride input; transformation and standardisation follow the final protocol"
    ),
    (
        "LBDHDD", "HDL", "Lipids",
        "Direct HDL cholesterol concentration",
        "mg/dL", "Proposed outcome component",
        "Continuous HDL input; direction reversed so lower HDL increases the proposed score"
    ),
    (
        "WHtR", "Derived", "Anthropometric index",
        "Waist-to-height ratio",
        "BMXWAIST / BMXHT using matching units",
        "Derived predictor",
        "Compared with BMI and included in prespecified predictor combinations"
    ),
    (
        "BRI", "Derived", "Anthropometric index",
        "Body Roundness Index",
        "Calculated from waist circumference and height",
        "Candidate derived predictor",
        "Optional secondary comparison; final predictor sets must be prespecified"
    ),
    (
        "ABSI", "Derived", "Anthropometric index",
        "A Body Shape Index",
        "Calculated from waist, BMI and height using consistent units",
        "Candidate derived predictor",
        "Optional secondary comparison; final predictor sets must be prespecified"
    ),
    (
        "Cardiometabolic_Score", "Derived — proposed",
        "Research outcome",
        "Proposed continuous clustered cardiometabolic score excluding body measurements",
        "Standardised continuous score; not a probability or clinical risk category",
        "Proposed dependent variable",
        "Based on BP, glucose, insulin, triglycerides and HDL; exact formula, references and medication policy must be locked before calculation"
    )
]

research_dictionary = pd.DataFrame(
    research_variable_rows,
    columns=[
        "Variable",
        "Source_Dataset",
        "Category",
        "Description",
        "Unit_or_Coding",
        "Research_Role",
        "Use_in_Project"
    ]
)

# Retain this variable name for compatibility with other notebook cells.
research_variables = research_dictionary.to_dict(orient="records")

display(research_dictionary)

,Variable,Source_Dataset,Category,Description,Unit_or_Coding,Research_Role,Use_in_Project
0,SEQN,All datasets,Identifier,Unique NHANES participant identification number,Participant ID,Merge key,Links participant records within each survey c...
1,RIDAGEYR,DEMO,Demographic,Participant age at screening,Years,Predictor and eligibility,Included in prediction models; final adult age...
2,RIAGENDR,DEMO,Demographic,Participant sex as recorded by NHANES,1 = Male; 2 = Female,Predictor and score reference,Model predictor; used for sex-specific standar...
3,RIDEXPRG,DEMO,Eligibility,Pregnancy status at examination,1 = Positive; 2 = Negative; 3 = Cannot ascertain,Eligibility audit,Assess pregnancy exclusion; missing or unknown...
4,SDMVPSU,DEMO,Survey design,Masked primary sampling unit,NHANES survey-design code,Survey design,Retained for survey-design-aware analysis
5,SDMVSTRA,DEMO,Survey design,Masked variance stratum,NHANES survey-design code,Survey design,Retained for survey-design-aware analysis
6,WTSAF2YR,GLU / TRIGLY / INS,Survey weight,Two-year fasting-subsample weight,Survey weight,Analysis weight,Compare across laboratory files before retaini...
7,PHAFSTHR,INS; also GLU where available,Fasting audit,Reported fasting duration: hours component,Hours,Eligibility and quality audit,Combine with PHAFSTMN to assess fasting duration
8,PHAFSTMN,INS; also GLU where available,Fasting audit,Reported fasting duration: minutes component,Minutes,Eligibility and quality audit,Combine with PHAFSTHR; apply the agreed fastin...
9,BMXHT,BMX,Anthropometric,Standing height,Centimetres,Index calculation input,"Used to calculate WHtR, BRI and ABSI and to ch..."
10,BMXWT,BMX,Anthropometric,Measured body weight,Kilograms,Index calculation input,Used to calculate or check BMI and audit body ...
11,BMXWAIST,BMX,Anthropometric,Measured waist circumference,Centimetres,Index calculation input,"Used to calculate WHtR, BRI and ABSI; excluded..."
12,BMXBMI,BMX,Anthropometric,NHANES body mass index,kg/m²,Predictor,Used in the BMI comparison model
13,BPXSY1–BPXSY4,BPX,Blood pressure,Repeated systolic blood-pressure measurements,mmHg,Outcome construction input,Eligible readings are averaged according to th...
14,BPXDI1–BPXDI4,BPX,Blood pressure,Repeated diastolic blood-pressure measurements,mmHg,Outcome construction input,Eligible readings are averaged according to th...
15,BPQ020,BPQ,Hypertension history,Ever told by a health professional that partic...,Use cycle-specific codebook,History and sensitivity audit,Describes hypertension history; not directly a...
16,BPQ040A,BPQ,Hypertension treatment,Ever advised to take prescribed medicine for h...,Use cycle-specific codebook,Treatment-history audit,Records treatment advice; does not alone estab...
17,BPQ050A,BPQ,Hypertension treatment,Currently taking prescribed medicine for high ...,Use cycle-specific codebook and questionnaire ...,Medication audit,Assess current treatment; final treatment-hand...
18,LBXGLU,GLU,Glycaemia,Fasting plasma glucose,mg/dL,Proposed outcome component,Continuous glucose input; transformation and r...
19,LBXIN,INS,Insulin,Measured serum insulin concentration,µU/mL,Proposed outcome component,Continuous insulin input; distinct from insuli...
20,LBDINSI,INS,Insulin,Serum insulin concentration in SI units,pmol/L,Supporting laboratory variable,Alternative units for insulin; not a separate ...
21,LBDINLC,INS,Laboratory quality,Insulin detection-limit comment code,0 = At or above detection limit; 1 = Below det...,Laboratory quality audit,Identify results below the detection limit and...
22,DIQ050,DIQ,Diabetes treatment,Currently taking insulin,Use cycle-specific codebook and questionnaire ...,Medication audit,Identifies insulin treatment; does not substit...
23,DIQ070,DIQ,Diabetes treatment,Currently taking diabetic pills to lower blood...,Use cycle-specific codebook and questionnaire ...,Medication audit,Assess glucose-lowering treatment under the fi...
24,LBXTR,TRIGLY,Lipids,Fasting triglyceride concentration,mg/dL,Proposed outcome component,Continuous triglyceride input; transformation ...
25,LBDHDD,HDL,Lipids,Direct HDL cholesterol concentration,mg/dL,Proposed outcome component,Continuous HDL input; direction reversed so lo...
26,WHtR,Derived,Anthropometric index,Waist-to-height ratio,BMXWAIST / BMXHT using matching units,Derived predictor,Compared with BMI and included in prespecified...
27,BRI,Derived,Anthropometric index,Body Roundness Index,Calculated from waist circumference and height,Candidate derived predictor,Optional secondary comparison; final predictor...
28,ABSI,Derived,Anthropometric index,A Body Shape Index,"Calculated from waist, BMI and height using co...",Candidate derived predictor,Optional secondary comparison; final predictor...
29,Cardiometabolic_Score,Derived — proposed,Research outcome,Proposed continuous clustered cardiometabolic ...,Standardised continuous score; not a probabili...,Proposed dependent variable,"Based on BP, glucose, insulin, triglycerides a..."

In [13]:
from pathlib import Path
from openpyxl.styles import Font, PatternFill, Alignment

dataset_register = pd.DataFrame([
    ["DEMO", "Demographics and survey design",
     "Age, sex, pregnancy status, strata and PSU", "Primary"],

    ["BMX", "Body measurements",
     "Height, weight, waist circumference and BMI", "Primary"],

    ["BPX", "Blood-pressure examination",
     "Repeated systolic and diastolic readings", "Primary"],

    ["BPQ", "Blood-pressure questionnaire",
     "Hypertension history, treatment advice and current medication", "Primary"],

    ["GLU", "Plasma fasting glucose",
     "Fasting glucose and fasting-subsample weight", "Primary"],

    ["INS", "Serum insulin",
     "Measured insulin, detection-limit flag, fasting duration and fasting-subsample weight", "Primary"],

    ["DIQ", "Diabetes questionnaire",
     "Insulin medication and diabetic-pill use", "Primary"],

    ["TRIGLY", "Triglycerides",
     "Fasting triglycerides and fasting-subsample weight", "Primary"],

    ["HDL", "HDL cholesterol",
     "Direct HDL cholesterol measurement", "Primary"],

    ["DR1TOT", "Dietary intake",
     "First-day total nutrient intake", "Secondary"],

    ["PAQ", "Physical activity",
     "Self-reported physical-activity information", "Secondary"]
], columns=[
    "Dataset",
    "Description",
    "Information_Used",
    "Analysis_Priority"
])

# Use the existing extracted-file list, including INS_H, INS_I and INS_J.
inventory_files = sorted(
    [Path(file) for file in extracted_xpt_files],
    key=lambda file: str(file)
)

if not inventory_files:
    raise ValueError("No extracted XPT files were found.")

raw_column_inventory = []
total_files = len(inventory_files)

print("Building technical column inventory")
print("=" * 70)

for number, xpt_path in enumerate(inventory_files, start=1):

    cycle = xpt_path.parent.name
    dataset_name = xpt_path.stem.upper()

    dataframe = pd.read_sas(
        xpt_path,
        format="xport",
        encoding="latin-1"
    )

    for column in dataframe.columns:

        non_missing = int(dataframe[column].notna().sum())
        missing = int(dataframe[column].isna().sum())
        unique_values = int(dataframe[column].nunique(dropna=True))

        examples = (
            dataframe[column]
            .dropna()
            .astype(str)
            .drop_duplicates()
            .head(3)
            .tolist()
        )

        raw_column_inventory.append({
            "Survey_Cycle": cycle,
            "Dataset": dataset_name,
            "Variable": column,
            "Data_Type": str(dataframe[column].dtype),
            "Total_Rows": len(dataframe),
            "Non_Missing": non_missing,
            "Missing": missing,
            "Missing_Percent": (
                missing / len(dataframe)
                if len(dataframe) > 0
                else None
            ),
            "Unique_Non_Missing": unique_values,
            "Example_Values": ", ".join(examples)
        })

    print(
        f"{number:02d}/{total_files} | {cycle} | "
        f"{dataset_name} | {len(dataframe.columns)} variables"
    )

raw_columns_dictionary = pd.DataFrame(raw_column_inventory)

dictionary_folder = project_folder / "data_dictionary"
dictionary_folder.mkdir(parents=True, exist_ok=True)

dictionary_file = dictionary_folder / "NHANES_Data_Dictionary.xlsx"

with pd.ExcelWriter(dictionary_file, engine="openpyxl") as writer:

    research_dictionary.to_excel(
        writer, sheet_name="Research_Variables", index=False
    )

    dataset_register.to_excel(
        writer, sheet_name="Dataset_Register", index=False
    )

    raw_columns_dictionary.to_excel(
        writer, sheet_name="All_Raw_Columns", index=False
    )

    for worksheet in writer.book.worksheets:

        worksheet.freeze_panes = "A2"
        worksheet.auto_filter.ref = worksheet.dimensions

        for cell in worksheet[1]:
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill(
                fill_type="solid",
                fgColor="1F4E78"
            )
            cell.alignment = Alignment(
                horizontal="center",
                vertical="center",
                wrap_text=True
            )

        worksheet.row_dimensions[1].height = 30

        for column_cells in worksheet.columns:

            column_letter = column_cells[0].column_letter

            maximum_length = max(
                len(str(cell.value)) if cell.value is not None else 0
                for cell in list(column_cells)[:250]
            )

            worksheet.column_dimensions[column_letter].width = min(
                maximum_length + 2,
                45
            )

    # Find the percentage column by its header.
    raw_sheet = writer.book["All_Raw_Columns"]

    percentage_column = next(
        cell.column
        for cell in raw_sheet[1]
        if cell.value == "Missing_Percent"
    )

    for row in raw_sheet.iter_rows(
        min_row=2,
        min_col=percentage_column,
        max_col=percentage_column
    ):
        row[0].number_format = "0.0%"

print("\nDATA DICTIONARY CREATED")
print("-" * 70)
print("Workbook:", dictionary_file)
print("Research variables:", len(research_dictionary))
print("Dataset types:", len(dataset_register))
print("Raw-column records:", len(raw_columns_dictionary))
print("Status: Successfully saved.")

Building technical column inventory
======================================================================
01/33 | 2013_2014 | BMX_H | 26 variables
02/33 | 2013_2014 | BPQ_H | 14 variables
03/33 | 2013_2014 | BPX_H | 23 variables
04/33 | 2013_2014 | DEMO_H | 47 variables
05/33 | 2013_2014 | DIQ_H | 54 variables
06/33 | 2013_2014 | DR1TOT_H | 168 variables
07/33 | 2013_2014 | GLU_H | 6 variables
08/33 | 2013_2014 | HDL_H | 3 variables
09/33 | 2013_2014 | INS_H | 6 variables
10/33 | 2013_2014 | PAQ_H | 96 variables
11/33 | 2013_2014 | TRIGLY_H | 6 variables
12/33 | 2015_2016 | BMX_I | 26 variables
13/33 | 2015_2016 | BPQ_I | 11 variables
14/33 | 2015_2016 | BPX_I | 21 variables
15/33 | 2015_2016 | DEMO_I | 47 variables
16/33 | 2015_2016 | DIQ_I | 54 variables
17/33 | 2015_2016 | DR1TOT_I | 168 variables
18/33 | 2015_2016 | GLU_I | 4 variables
19/33 | 2015_2016 | HDL_I | 3 variables
20/33 | 2015_2016 | INS_I | 7 variables
21/33 | 2015_2016 | PAQ_I | 94 variables
22/33 | 2015_2016 | TRIGLY_I | 6 variables
23/33 | 2017_2018 | BMX_J | 21 variables
24/33 | 2017_2018 | BPQ_J | 11 variables
25/33 | 2017_2018 | BPX_J | 21 variables
26/33 | 2017_2018 | DEMO_J | 46 variables
27/33 | 2017_2018 | DIQ_J | 54 variables
28/33 | 2017_2018 | DR1TOT_J | 168 variables
29/33 | 2017_2018 | GLU_J | 4 variables
30/33 | 2017_2018 | HDL_J | 3 variables
31/33 | 2017_2018 | INS_J | 5 variables
32/33 | 2017_2018 | PAQ_J | 17 variables
33/33 | 2017_2018 | TRIGLY_J | 10 variables

DATA DICTIONARY CREATED
----------------------------------------------------------------------
Workbook: /content/drive/MyDrive/NHANES_Project/data_dictionary/NHANES_Data_Dictionary.xlsx
Research variables: 30
Dataset types: 11
Raw-column records: 1250
Status: Successfully saved.

In [15]:
cycle_suffixes = {
    "2013_2014": "H",
    "2015_2016": "I",
    "2017_2018": "J"
}

dataset_codes = dataset_register["Dataset"].tolist()

expected_excel_files = {
    f"{cycle}/{dataset}_{suffix}.xlsx".upper()
    for cycle, suffix in cycle_suffixes.items()
    for dataset in dataset_codes
}

excel_files = sorted(
    file
    for file in excel_root.rglob("*")
    if file.is_file()
    and file.suffix.lower() == ".xlsx"
    and not file.name.startswith("~$")
)

found_excel_files = {
    file.relative_to(excel_root).as_posix().upper()
    for file in excel_files
}

missing_files = expected_excel_files - found_excel_files
unexpected_files = found_excel_files - expected_excel_files

# Reset issues whenever this cell is rerun.
audit_issues = []

# Each cycle has its own expected insulin columns.
insulin_required_columns_by_dataset = {
    "INS_H": {
        "SEQN",
        "LBXIN",
        "LBDINSI",
        "WTSAF2YR",
        "PHAFSTHR",
        "PHAFSTMN"
    },
    "INS_I": {
        "SEQN",
        "LBXIN",
        "LBDINSI",
        "LBDINLC",
        "WTSAF2YR",
        "PHAFSTHR",
        "PHAFSTMN"
    },
    "INS_J": {
        "SEQN",
        "LBXIN",
        "LBDINSI",
        "LBDINLC",
        "WTSAF2YR"
    }
}

print("FINAL EXTRACTION AUDIT")
print("-" * 70)
print("Expected Excel datasets:", len(expected_excel_files))
print("Excel datasets found:", len(excel_files))
print("Extraction summary exists:", summary_file.exists())
print("Data dictionary exists:", dictionary_file.exists())

for cycle in cycle_suffixes:

    cycle_files = [
        file
        for file in excel_files
        if file.parent == excel_root / cycle
    ]

    print(
        f"{cycle}: {len(cycle_files)} Excel files "
        f"(expected {len(dataset_codes)})"
    )

if missing_files:
    print("\nMissing files:")
    for name in sorted(missing_files):
        print(" -", name)

if unexpected_files:
    print("\nUnexpected files:")
    for name in sorted(unexpected_files):
        print(" -", name)

print("\nWORKBOOK CONTENT CHECKS")
print("-" * 70)

for file in excel_files:

    relative_name = file.relative_to(excel_root).as_posix()
    normalised_name = relative_name.upper()

    if normalised_name not in expected_excel_files:
        continue

    try:
        dataframe = pd.read_excel(
            file,
            sheet_name="Raw_Data"
        )

        if dataframe.empty:
            audit_issues.append(
                f"{relative_name}: no participant rows"
            )

        if "SEQN" not in dataframe.columns:
            audit_issues.append(
                f"{relative_name}: SEQN column missing"
            )
        else:
            if dataframe["SEQN"].isna().any():
                audit_issues.append(
                    f"{relative_name}: missing SEQN values"
                )

            if dataframe["SEQN"].duplicated().any():
                audit_issues.append(
                    f"{relative_name}: duplicate SEQN values"
                )

        dataset_name = file.stem.upper()

        if dataset_name in insulin_required_columns_by_dataset:

            required_columns = (
                insulin_required_columns_by_dataset[dataset_name]
            )

            missing_columns = (
                required_columns - set(dataframe.columns)
            )

            if missing_columns:
                audit_issues.append(
                    f"{relative_name}: missing expected insulin columns "
                    f"{sorted(missing_columns)}"
                )
            else:
                print(
                    f"{relative_name}: "
                    "cycle-specific column check passed"
                )

            if "LBXIN" in dataframe.columns:
                print(
                    f"  {len(dataframe):,} rows; "
                    f"{dataframe['LBXIN'].notna().sum():,} insulin results; "
                    f"{dataframe['LBXIN'].isna().sum():,} missing insulin results"
                )

    except Exception as error:
        audit_issues.append(
            f"{relative_name}: {error}"
        )

# Check that the column inventory includes every expected dataset.
expected_inventory_pairs = {
    (cycle, f"{dataset}_{suffix}")
    for cycle, suffix in cycle_suffixes.items()
    for dataset in dataset_codes
}

actual_inventory_pairs = set(
    raw_columns_dictionary[
        ["Survey_Cycle", "Dataset"]
    ].itertuples(index=False, name=None)
)

missing_inventory = (
    expected_inventory_pairs - actual_inventory_pairs
)

if missing_inventory:
    audit_issues.append(
        "Datasets missing from column inventory: "
        f"{sorted(missing_inventory)}"
    )

if audit_issues:
    print("\nIssues requiring attention:")
    for issue in audit_issues:
        print(" -", issue)

extraction_complete = (
    not missing_files
    and not unexpected_files
    and len(excel_files) == len(expected_excel_files)
    and summary_file.exists()
    and dictionary_file.exists()
    and not audit_issues
)

if extraction_complete:
    print("\nStatus: DATA EXTRACTION CHECKS PASSED")
    print(
        "Next step: update merging and run "
        "participant-level eligibility checks."
    )
else:
    print("\nStatus: CHECK THE ISSUES ABOVE BEFORE CONTINUING")

FINAL EXTRACTION AUDIT
----------------------------------------------------------------------
Expected Excel datasets: 33
Excel datasets found: 33
Extraction summary exists: True
Data dictionary exists: True
2013_2014: 11 Excel files (expected 11)
2015_2016: 11 Excel files (expected 11)
2017_2018: 11 Excel files (expected 11)

WORKBOOK CONTENT CHECKS
----------------------------------------------------------------------
2013_2014/INS_H.xlsx: cycle-specific column check passed
  3,329 rows; 3,093 insulin results; 236 missing insulin results
2015_2016/INS_I.xlsx: cycle-specific column check passed
  3,191 rows; 2,921 insulin results; 270 missing insulin results
2017_2018/INS_J.xlsx: cycle-specific column check passed
  3,036 rows; 2,825 insulin results; 211 missing insulin results

Status: DATA EXTRACTION CHECKS PASSED
Next step: update merging and run participant-level eligibility checks.