<a href="https://colab.research.google.com/github/Heashalla/FYP/blob/main/01_data_extraction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NHANES Cardiometabolic-Risk Project

## Notebook 01: Raw Data Extraction

This notebook imports and inspects the original NHANES XPT files for the 2013–2014, 2015–2016 and 2017–2018 survey cycles.

In [1]:
from google.colab import drive

drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
from pathlib import Path

project_folder = Path("/content/drive/MyDrive/NHANES_Project")
zip_file = project_folder / "NHANES_raw_data.zip"

print("Project folder:", project_folder)
print("Project folder exists:", project_folder.exists())
print()
print("ZIP file:", zip_file)
print("ZIP file exists:", zip_file.exists())

if zip_file.exists():
    size_mb = zip_file.stat().st_size / (1024 * 1024)
    print(f"ZIP file size: {size_mb:.2f} MB")
    print("\nStatus: ZIP file located successfully.")
else:
    print("\nStatus: ZIP file was not found.")

Project folder: /content/drive/MyDrive/NHANES_Project
Project folder exists: True

ZIP file: /content/drive/MyDrive/NHANES_Project/NHANES_raw_data.zip
ZIP file exists: True
ZIP file size: 10.49 MB

Status: ZIP file located successfully.

In [5]:
import zipfile
from pathlib import Path

with zipfile.ZipFile(zip_file, "r") as zip_archive:
    all_entries = zip_archive.namelist()

# Exclude folder entries
files_inside = [
    entry for entry in all_entries
    if not entry.endswith("/")
]

# Select XPT files regardless of upper/lowercase extension
xpt_files = [
    entry for entry in files_inside
    if Path(entry).suffix.lower() == ".xpt"
]

other_files = [
    entry for entry in files_inside
    if Path(entry).suffix.lower() != ".xpt"
]

print("ZIP inspection completed")
print("-" * 60)
print("Total files found:", len(files_inside))
print("XPT files found:", len(xpt_files))
print("Other files found:", len(other_files))

print("\nXPT FILES")
print("-" * 60)

for number, file_name in enumerate(sorted(xpt_files), start=1):
    print(f"{number:02d}. {file_name}")

if other_files:
    print("\nOTHER FILES")
    print("-" * 60)

    for file_name in sorted(other_files):
        print(file_name)

print("\nVALIDATION")
print("-" * 60)

if len(xpt_files) == 30:
    print("Status: All 30 expected XPT files were found.")
else:
    print(f"Status: Expected 30 XPT files, but found {len(xpt_files)}.")

ZIP inspection completed
------------------------------------------------------------
Total files found: 30
XPT files found: 30
Other files found: 0

XPT FILES
------------------------------------------------------------
01. raw_data/2013_2014/BMX_H.XPT
02. raw_data/2013_2014/BPQ_H.XPT
03. raw_data/2013_2014/BPX_H.XPT
04. raw_data/2013_2014/DEMO_H.XPT
05. raw_data/2013_2014/DIQ_H.XPT
06. raw_data/2013_2014/DR1TOT_H.XPT
07. raw_data/2013_2014/GLU_H.xpt
08. raw_data/2013_2014/HDL_H.XPT
09. raw_data/2013_2014/PAQ_H.XPT
10. raw_data/2013_2014/TRIGLY_H.XPT
11. raw_data/2015_2016/BMX_I.XPT
12. raw_data/2015_2016/BPQ_I.XPT
13. raw_data/2015_2016/BPX_I.XPT
14. raw_data/2015_2016/DEMO_I.XPT
15. raw_data/2015_2016/DIQ_I.XPT
16. raw_data/2015_2016/DR1TOT_I.XPT
17. raw_data/2015_2016/GLU_I.xpt
18. raw_data/2015_2016/HDL_I.XPT
19. raw_data/2015_2016/PAQ_I.XPT
20. raw_data/2015_2016/TRIGLY_I.XPT
21. raw_data/2017_2018/BMX_J.XPT
22. raw_data/2017_2018/BPQ_J.XPT
23. raw_data/2017_2018/BPX_J.XPT
24. raw_data/2017_2018/DEMO_J.XPT
25. raw_data/2017_2018/DIQ_J.XPT
26. raw_data/2017_2018/DR1TOT_J.XPT
27. raw_data/2017_2018/GLU_J.xpt
28. raw_data/2017_2018/HDL_J.XPT
29. raw_data/2017_2018/PAQ_J.XPT
30. raw_data/2017_2018/TRIGLY_J.XPT

VALIDATION
------------------------------------------------------------
Status: All 30 expected XPT files were found.

In [6]:
expected_files = {
    "2013_2014": {
        "BMX_H.XPT", "BPQ_H.XPT", "BPX_H.XPT", "DEMO_H.XPT",
        "DIQ_H.XPT", "DR1TOT_H.XPT", "GLU_H.XPT", "HDL_H.XPT",
        "PAQ_H.XPT", "TRIGLY_H.XPT"
    },
    "2015_2016": {
        "BMX_I.XPT", "BPQ_I.XPT", "BPX_I.XPT", "DEMO_I.XPT",
        "DIQ_I.XPT", "DR1TOT_I.XPT", "GLU_I.XPT", "HDL_I.XPT",
        "PAQ_I.XPT", "TRIGLY_I.XPT"
    },
    "2017_2018": {
        "BMX_J.XPT", "BPQ_J.XPT", "BPX_J.XPT", "DEMO_J.XPT",
        "DIQ_J.XPT", "DR1TOT_J.XPT", "GLU_J.XPT", "HDL_J.XPT",
        "PAQ_J.XPT", "TRIGLY_J.XPT"
    }
}

all_cycles_valid = True

for cycle, expected in expected_files.items():

    found = {
        Path(file_name).name.upper()
        for file_name in xpt_files
        if cycle in file_name
    }

    missing = expected - found
    unexpected = found - expected

    print(f"\nCycle: {cycle}")
    print("-" * 40)
    print("Expected files:", len(expected))
    print("Files found:", len(found))

    if not missing and not unexpected:
        print("Status: Complete")
    else:
        all_cycles_valid = False
        print("Status: Check required")

        if missing:
            print("Missing files:", sorted(missing))

        if unexpected:
            print("Unexpected files:", sorted(unexpected))

print("\nOVERALL VALIDATION")
print("-" * 40)

if all_cycles_valid:
    print("Status: All three survey cycles are complete.")
    print("The ZIP file is ready for extraction.")
else:
    print("Status: One or more cycles require correction.")

Cycle: 2013_2014
----------------------------------------
Expected files: 10
Files found: 10
Status: Complete

Cycle: 2015_2016
----------------------------------------
Expected files: 10
Files found: 10
Status: Complete

Cycle: 2017_2018
----------------------------------------
Expected files: 10
Files found: 10
Status: Complete

OVERALL VALIDATION
----------------------------------------
Status: All three survey cycles are complete.
The ZIP file is ready for extraction.

In [7]:
import zipfile
from pathlib import Path

extraction_folder = Path("/content/NHANES_Project")
extraction_folder.mkdir(parents=True, exist_ok=True)

with zipfile.ZipFile(zip_file, "r") as zip_archive:
    zip_archive.extractall(extraction_folder)

raw_data_folder = extraction_folder / "raw_data"

extracted_xpt_files = sorted([
    file_path
    for file_path in raw_data_folder.rglob("*")
    if file_path.is_file() and file_path.suffix.lower() == ".xpt"
])

print("Extraction completed")
print("-" * 60)
print("Extraction folder:", extraction_folder)
print("Raw-data folder exists:", raw_data_folder.exists())
print("XPT files extracted:", len(extracted_xpt_files))

print("\nEXTRACTED FILES")
print("-" * 60)

for number, file_path in enumerate(extracted_xpt_files, start=1):
    relative_path = file_path.relative_to(extraction_folder)
    print(f"{number:02d}. {relative_path}")

print("\nVALIDATION")
print("-" * 60)

if len(extracted_xpt_files) == 30:
    print("Status: All 30 XPT files were extracted successfully.")
else:
    print(f"Status: Expected 30 files, but extracted {len(extracted_xpt_files)}.")

Extraction completed
------------------------------------------------------------
Extraction folder: /content/NHANES_Project
Raw-data folder exists: True
XPT files extracted: 30

EXTRACTED FILES
------------------------------------------------------------
01. raw_data/2013_2014/BMX_H.XPT
02. raw_data/2013_2014/BPQ_H.XPT
03. raw_data/2013_2014/BPX_H.XPT
04. raw_data/2013_2014/DEMO_H.XPT
05. raw_data/2013_2014/DIQ_H.XPT
06. raw_data/2013_2014/DR1TOT_H.XPT
07. raw_data/2013_2014/GLU_H.xpt
08. raw_data/2013_2014/HDL_H.XPT
09. raw_data/2013_2014/PAQ_H.XPT
10. raw_data/2013_2014/TRIGLY_H.XPT
11. raw_data/2015_2016/BMX_I.XPT
12. raw_data/2015_2016/BPQ_I.XPT
13. raw_data/2015_2016/BPX_I.XPT
14. raw_data/2015_2016/DEMO_I.XPT
15. raw_data/2015_2016/DIQ_I.XPT
16. raw_data/2015_2016/DR1TOT_I.XPT
17. raw_data/2015_2016/GLU_I.xpt
18. raw_data/2015_2016/HDL_I.XPT
19. raw_data/2015_2016/PAQ_I.XPT
20. raw_data/2015_2016/TRIGLY_I.XPT
21. raw_data/2017_2018/BMX_J.XPT
22. raw_data/2017_2018/BPQ_J.XPT
23. raw_data/2017_2018/BPX_J.XPT
24. raw_data/2017_2018/DEMO_J.XPT
25. raw_data/2017_2018/DIQ_J.XPT
26. raw_data/2017_2018/DR1TOT_J.XPT
27. raw_data/2017_2018/GLU_J.xpt
28. raw_data/2017_2018/HDL_J.XPT
29. raw_data/2017_2018/PAQ_J.XPT
30. raw_data/2017_2018/TRIGLY_J.XPT

VALIDATION
------------------------------------------------------------
Status: All 30 XPT files were extracted successfully.

In [8]:
import pandas as pd
from IPython.display import display

demo_h_path = raw_data_folder / "2013_2014" / "DEMO_H.XPT"

print("File:", demo_h_path.name)
print("File exists:", demo_h_path.exists())

demo_h = pd.read_sas(
    demo_h_path,
    format="xport",
    encoding="latin-1"
)

print("\nDATASET SUMMARY")
print("-" * 60)
print("Survey cycle: 2013–2014")
print("Number of rows:", demo_h.shape[0])
print("Number of columns:", demo_h.shape[1])
print("Duplicate SEQN values:", demo_h["SEQN"].duplicated().sum())
print("Total missing cells:", demo_h.isna().sum().sum())

print("\nCOLUMN NAMES")
print("-" * 60)
print(demo_h.columns.tolist())

print("\nFIRST FIVE PARTICIPANTS")
print("-" * 60)
display(demo_h.head())

File: DEMO_H.XPT
File exists: True

DATASET SUMMARY
------------------------------------------------------------
Survey cycle: 2013–2014
Number of rows: 10175
Number of columns: 47
Duplicate SEQN values: 0
Total missing cells: 82092

COLUMN NAMES
------------------------------------------------------------
['SEQN', 'SDDSRVYR', 'RIDSTATR', 'RIAGENDR', 'RIDAGEYR', 'RIDAGEMN', 'RIDRETH1', 'RIDRETH3', 'RIDEXMON', 'RIDEXAGM', 'DMQMILIZ', 'DMQADFC', 'DMDBORN4', 'DMDCITZN', 'DMDYRSUS', 'DMDEDUC3', 'DMDEDUC2', 'DMDMARTL', 'RIDEXPRG', 'SIALANG', 'SIAPROXY', 'SIAINTRP', 'FIALANG', 'FIAPROXY', 'FIAINTRP', 'MIALANG', 'MIAPROXY', 'MIAINTRP', 'AIALANGA', 'DMDHHSIZ', 'DMDFMSIZ', 'DMDHHSZA', 'DMDHHSZB', 'DMDHHSZE', 'DMDHRGND', 'DMDHRAGE', 'DMDHRBR4', 'DMDHREDU', 'DMDHRMAR', 'DMDHSEDU', 'WTINT2YR', 'WTMEC2YR', 'SDMVPSU', 'SDMVSTRA', 'INDHHIN2', 'INDFMIN2', 'INDFMPIR']

FIRST FIVE PARTICIPANTS
------------------------------------------------------------

,SEQN,SDDSRVYR,RIDSTATR,RIAGENDR,RIDAGEYR,RIDAGEMN,RIDRETH1,RIDRETH3,RIDEXMON,RIDEXAGM,...,DMDHREDU,DMDHRMAR,DMDHSEDU,WTINT2YR,WTMEC2YR,SDMVPSU,SDMVSTRA,INDHHIN2,INDFMIN2,INDFMPIR
0,73557.0,8.0,2.0,1.0,69.0,NaN,4.0,4.0,1.0,NaN,...,3.0,4.0,NaN,13281.237386,13481.042095,1.0,112.0,4.0,4.0,0.84
1,73558.0,8.0,2.0,1.0,54.0,NaN,3.0,3.0,1.0,NaN,...,3.0,1.0,1.0,23682.057386,24471.769625,1.0,108.0,7.0,7.0,1.78
2,73559.0,8.0,2.0,1.0,72.0,NaN,3.0,3.0,2.0,NaN,...,4.0,1.0,3.0,57214.803319,57193.285376,1.0,109.0,10.0,10.0,4.51
3,73560.0,8.0,2.0,1.0,9.0,NaN,3.0,3.0,1.0,119.0,...,3.0,1.0,4.0,55201.178592,55766.512438,2.0,109.0,9.0,9.0,2.52
4,73561.0,8.0,2.0,2.0,73.0,NaN,3.0,3.0,1.0,NaN,...,5.0,1.0,5.0,63709.667069,65541.871229,2.0,116.0,15.0,15.0,5.00

In [9]:
import pandas as pd
from pathlib import Path
from openpyxl.styles import Font, PatternFill, Alignment

# Permanent Excel output location in Google Drive
excel_root = project_folder / "raw_excel"
excel_root.mkdir(parents=True, exist_ok=True)

extraction_summary = []

print("Starting XPT-to-Excel conversion")
print("=" * 70)

for number, xpt_path in enumerate(extracted_xpt_files, start=1):

    cycle = xpt_path.parent.name

    cycle_output_folder = excel_root / cycle
    cycle_output_folder.mkdir(parents=True, exist_ok=True)

    excel_name = f"{xpt_path.stem.upper()}.xlsx"
    excel_path = cycle_output_folder / excel_name

    try:
        # Read the original XPT file
        dataframe = pd.read_sas(
            xpt_path,
            format="xport",
            encoding="latin-1"
        )

        # Display participant IDs as whole numbers in Excel
        if "SEQN" in dataframe.columns:
            dataframe["SEQN"] = pd.to_numeric(
                dataframe["SEQN"],
                errors="coerce"
            ).astype("Int64")

        duplicate_seqn = (
            int(dataframe["SEQN"].duplicated().sum())
            if "SEQN" in dataframe.columns
            else None
        )

        # Export to Excel
        with pd.ExcelWriter(
            excel_path,
            engine="openpyxl"
        ) as writer:

            dataframe.to_excel(
                writer,
                sheet_name="Raw_Data",
                index=False
            )

            worksheet = writer.book["Raw_Data"]

            # Keep the column names visible when scrolling
            worksheet.freeze_panes = "A2"

            # Add filters to the complete table
            worksheet.auto_filter.ref = worksheet.dimensions

            # Format the header row
            header_fill = PatternFill(
                fill_type="solid",
                fgColor="1F4E78"
            )

            for cell in worksheet[1]:
                cell.font = Font(
                    bold=True,
                    color="FFFFFF"
                )
                cell.fill = header_fill
                cell.alignment = Alignment(
                    horizontal="center"
                )

        extraction_summary.append({
            "Survey_Cycle": cycle,
            "XPT_File": xpt_path.name,
            "Excel_File": excel_name,
            "Rows": dataframe.shape[0],
            "Columns": dataframe.shape[1],
            "Duplicate_SEQN": duplicate_seqn,
            "Missing_Cells": int(dataframe.isna().sum().sum()),
            "Status": "Successfully converted"
        })

        print(
            f"{number:02d}/30 | {cycle} | "
            f"{xpt_path.name} → {excel_name} | "
            f"{dataframe.shape[0]:,} rows × "
            f"{dataframe.shape[1]} columns"
        )

    except Exception as error:

        extraction_summary.append({
            "Survey_Cycle": cycle,
            "XPT_File": xpt_path.name,
            "Excel_File": excel_name,
            "Rows": None,
            "Columns": None,
            "Duplicate_SEQN": None,
            "Missing_Cells": None,
            "Status": f"Failed: {error}"
        })

        print(
            f"{number:02d}/30 | FAILED | "
            f"{xpt_path.name} | {error}"
        )

print("=" * 70)
print("Conversion process completed.")

Starting XPT-to-Excel conversion
======================================================================
01/30 | 2013_2014 | BMX_H.XPT → BMX_H.xlsx | 9,813 rows × 26 columns
02/30 | 2013_2014 | BPQ_H.XPT → BPQ_H.xlsx | 6,464 rows × 14 columns
03/30 | 2013_2014 | BPX_H.XPT → BPX_H.xlsx | 9,813 rows × 23 columns
04/30 | 2013_2014 | DEMO_H.XPT → DEMO_H.xlsx | 10,175 rows × 47 columns
05/30 | 2013_2014 | DIQ_H.XPT → DIQ_H.xlsx | 9,770 rows × 54 columns
06/30 | 2013_2014 | DR1TOT_H.XPT → DR1TOT_H.xlsx | 9,813 rows × 168 columns
07/30 | 2013_2014 | GLU_H.xpt → GLU_H.xlsx | 3,329 rows × 6 columns
08/30 | 2013_2014 | HDL_H.XPT → HDL_H.xlsx | 8,291 rows × 3 columns
09/30 | 2013_2014 | PAQ_H.XPT → PAQ_H.xlsx | 9,484 rows × 96 columns
10/30 | 2013_2014 | TRIGLY_H.XPT → TRIGLY_H.xlsx | 3,329 rows × 6 columns
11/30 | 2015_2016 | BMX_I.XPT → BMX_I.xlsx | 9,544 rows × 26 columns
12/30 | 2015_2016 | BPQ_I.XPT → BPQ_I.xlsx | 6,327 rows × 11 columns
13/30 | 2015_2016 | BPX_I.XPT → BPX_I.xlsx | 9,544 rows × 21 columns
14/30 | 2015_2016 | DEMO_I.XPT → DEMO_I.xlsx | 9,971 rows × 47 columns
15/30 | 2015_2016 | DIQ_I.XPT → DIQ_I.xlsx | 9,575 rows × 54 columns
16/30 | 2015_2016 | DR1TOT_I.XPT → DR1TOT_I.xlsx | 9,544 rows × 168 columns
17/30 | 2015_2016 | GLU_I.xpt → GLU_I.xlsx | 3,191 rows × 4 columns
18/30 | 2015_2016 | HDL_I.XPT → HDL_I.xlsx | 8,021 rows × 3 columns
19/30 | 2015_2016 | PAQ_I.XPT → PAQ_I.xlsx | 9,255 rows × 94 columns
20/30 | 2015_2016 | TRIGLY_I.XPT → TRIGLY_I.xlsx | 3,191 rows × 6 columns
21/30 | 2017_2018 | BMX_J.XPT → BMX_J.xlsx | 8,704 rows × 21 columns
22/30 | 2017_2018 | BPQ_J.XPT → BPQ_J.xlsx | 6,161 rows × 11 columns
23/30 | 2017_2018 | BPX_J.XPT → BPX_J.xlsx | 8,704 rows × 21 columns
24/30 | 2017_2018 | DEMO_J.XPT → DEMO_J.xlsx | 9,254 rows × 46 columns
25/30 | 2017_2018 | DIQ_J.XPT → DIQ_J.xlsx | 8,897 rows × 54 columns
26/30 | 2017_2018 | DR1TOT_J.XPT → DR1TOT_J.xlsx | 8,704 rows × 168 columns
27/30 | 2017_2018 | GLU_J.xpt → GLU_J.xlsx | 3,036 rows × 4 columns
28/30 | 2017_2018 | HDL_J.XPT → HDL_J.xlsx | 7,435 rows × 3 columns
29/30 | 2017_2018 | PAQ_J.XPT → PAQ_J.xlsx | 5,856 rows × 17 columns
30/30 | 2017_2018 | TRIGLY_J.XPT → TRIGLY_J.xlsx | 3,036 rows × 10 columns
======================================================================
Conversion process completed.

In [10]:
summary_dataframe = pd.DataFrame(extraction_summary)

reports_folder = project_folder / "reports"
reports_folder.mkdir(parents=True, exist_ok=True)

summary_file = reports_folder / "extraction_summary.xlsx"

summary_dataframe.to_excel(
    summary_file,
    sheet_name="Extraction_Summary",
    index=False
)

successful_files = (
    summary_dataframe["Status"] == "Successfully converted"
).sum()

failed_files = len(summary_dataframe) - successful_files

print("EXTRACTION SUMMARY")
print("-" * 70)
print("Files processed:", len(summary_dataframe))
print("Successfully converted:", successful_files)
print("Failed conversions:", failed_files)
print("Excel output folder:", excel_root)
print("Summary report:", summary_file)

display(summary_dataframe)

EXTRACTION SUMMARY
----------------------------------------------------------------------
Files processed: 30
Successfully converted: 30
Failed conversions: 0
Excel output folder: /content/drive/MyDrive/NHANES_Project/raw_excel
Summary report: /content/drive/MyDrive/NHANES_Project/reports/extraction_summary.xlsx

,Survey_Cycle,XPT_File,Excel_File,Rows,Columns,Duplicate_SEQN,Missing_Cells,Status
0,2013_2014,BMX_H.XPT,BMX_H.xlsx,9813,26,0,143166,Successfully converted
1,2013_2014,BPQ_H.XPT,BPQ_H.xlsx,6464,14,0,33153,Successfully converted
2,2013_2014,BPX_H.XPT,BPX_H.xlsx,9813,23,0,78847,Successfully converted
3,2013_2014,DEMO_H.XPT,DEMO_H.xlsx,10175,47,0,82092,Successfully converted
4,2013_2014,DIQ_H.XPT,DIQ_H.xlsx,9770,54,0,453621,Successfully converted
5,2013_2014,DR1TOT_H.XPT,DR1TOT_H.xlsx,9813,168,0,704978,Successfully converted
6,2013_2014,GLU_H.xpt,GLU_H.xlsx,3329,6,0,390,Successfully converted
7,2013_2014,HDL_H.XPT,HDL_H.xlsx,8291,3,0,1334,Successfully converted
8,2013_2014,PAQ_H.XPT,PAQ_H.xlsx,9484,96,0,775493,Successfully converted
9,2013_2014,TRIGLY_H.XPT,TRIGLY_H.xlsx,3329,6,0,814,Successfully converted
10,2015_2016,BMX_I.XPT,BMX_I.xlsx,9544,26,0,139669,Successfully converted
11,2015_2016,BPQ_I.XPT,BPQ_I.xlsx,6327,11,0,27329,Successfully converted
12,2015_2016,BPX_I.XPT,BPX_I.xlsx,9544,21,0,76311,Successfully converted
13,2015_2016,DEMO_I.XPT,DEMO_I.xlsx,9971,47,0,82430,Successfully converted
14,2015_2016,DIQ_I.XPT,DIQ_I.xlsx,9575,54,0,441440,Successfully converted
15,2015_2016,DR1TOT_I.XPT,DR1TOT_I.xlsx,9544,168,0,684306,Successfully converted
16,2015_2016,GLU_I.xpt,GLU_I.xlsx,3191,4,0,438,Successfully converted
17,2015_2016,HDL_I.XPT,HDL_I.xlsx,8021,3,0,1530,Successfully converted
18,2015_2016,PAQ_I.XPT,PAQ_I.xlsx,9255,94,0,747153,Successfully converted
19,2015_2016,TRIGLY_I.XPT,TRIGLY_I.xlsx,3191,6,0,1920,Successfully converted
20,2017_2018,BMX_J.XPT,BMX_J.xlsx,8704,21,0,100717,Successfully converted
21,2017_2018,BPQ_J.XPT,BPQ_J.xlsx,6161,11,0,26003,Successfully converted
22,2017_2018,BPX_J.XPT,BPX_J.xlsx,8704,21,0,70095,Successfully converted
23,2017_2018,DEMO_J.XPT,DEMO_J.xlsx,9254,46,0,77531,Successfully converted
24,2017_2018,DIQ_J.XPT,DIQ_J.xlsx,8897,54,0,406660,Successfully converted
25,2017_2018,DR1TOT_J.XPT,DR1TOT_J.xlsx,8704,168,0,637156,Successfully converted
26,2017_2018,GLU_J.xpt,GLU_J.xlsx,3036,4,0,290,Successfully converted
27,2017_2018,HDL_J.XPT,HDL_J.xlsx,7435,3,0,1394,Successfully converted
28,2017_2018,PAQ_J.XPT,PAQ_J.xlsx,5856,17,0,40592,Successfully converted
29,2017_2018,TRIGLY_J.XPT,TRIGLY_J.xlsx,3036,10,0,1734,Successfully converted

In [11]:
research_variables = [
    {
        "Variable": "SEQN",
        "Source_Dataset": "All datasets",
        "Category": "Identifier",
        "Description": "Unique NHANES participant identification number",
        "Unit_or_Coding": "Participant ID",
        "Research_Role": "Merge key",
        "Use_in_Project": "Links records belonging to the same participant"
    },
    {
        "Variable": "RIDAGEYR",
        "Source_Dataset": "DEMO",
        "Category": "Demographic",
        "Description": "Participant age at screening",
        "Unit_or_Coding": "Years",
        "Research_Role": "Predictor",
        "Use_in_Project": "Adults aged 20–79; included in prediction models"
    },
    {
        "Variable": "RIAGENDR",
        "Source_Dataset": "DEMO",
        "Category": "Demographic",
        "Description": "Participant sex",
        "Unit_or_Coding": "1 = Male; 2 = Female",
        "Research_Role": "Predictor",
        "Use_in_Project": "Converted into a model-ready sex indicator"
    },
    {
        "Variable": "SDMVPSU",
        "Source_Dataset": "DEMO",
        "Category": "Survey design",
        "Description": "Masked primary sampling unit",
        "Unit_or_Coding": "NHANES survey-design code",
        "Research_Role": "Survey design",
        "Use_in_Project": "Used for survey-weighted variance estimation"
    },
    {
        "Variable": "SDMVSTRA",
        "Source_Dataset": "DEMO",
        "Category": "Survey design",
        "Description": "Masked variance stratum",
        "Unit_or_Coding": "NHANES survey-design code",
        "Research_Role": "Survey design",
        "Use_in_Project": "Used for survey-weighted variance estimation"
    },
    {
        "Variable": "WTSAF2YR",
        "Source_Dataset": "GLU / TRIGLY",
        "Category": "Survey weight",
        "Description": "Two-year fasting-subsample examination weight",
        "Unit_or_Coding": "Survey weight",
        "Research_Role": "Analysis weight",
        "Use_in_Project": "Required because fasting glucose and triglycerides use the fasting subsample"
    },
    {
        "Variable": "BMXHT",
        "Source_Dataset": "BMX",
        "Category": "Anthropometric",
        "Description": "Standing height",
        "Unit_or_Coding": "Centimetres",
        "Research_Role": "Input predictor",
        "Use_in_Project": "Used to calculate WHtR, BRI and ABSI"
    },
    {
        "Variable": "BMXWT",
        "Source_Dataset": "BMX",
        "Category": "Anthropometric",
        "Description": "Measured body weight",
        "Unit_or_Coding": "Kilograms",
        "Research_Role": "Supporting variable",
        "Use_in_Project": "Used for body-measurement checks"
    },
    {
        "Variable": "BMXWAIST",
        "Source_Dataset": "BMX",
        "Category": "Anthropometric",
        "Description": "Measured waist circumference",
        "Unit_or_Coding": "Centimetres",
        "Research_Role": "Input predictor",
        "Use_in_Project": "Used to calculate WHtR, BRI and ABSI"
    },
    {
        "Variable": "BMXBMI",
        "Source_Dataset": "BMX",
        "Category": "Anthropometric",
        "Description": "Body mass index",
        "Unit_or_Coding": "kg/m²",
        "Research_Role": "Predictor",
        "Use_in_Project": "BMI comparison model and normal-BMI subgroup"
    },
    {
        "Variable": "BPXSY1–BPXSY4",
        "Source_Dataset": "BPX",
        "Category": "Blood pressure",
        "Description": "Repeated systolic blood-pressure measurements",
        "Unit_or_Coding": "mmHg",
        "Research_Role": "Outcome component",
        "Use_in_Project": "Available readings are averaged"
    },
    {
        "Variable": "BPXDI1–BPXDI4",
        "Source_Dataset": "BPX",
        "Category": "Blood pressure",
        "Description": "Repeated diastolic blood-pressure measurements",
        "Unit_or_Coding": "mmHg",
        "Research_Role": "Outcome component",
        "Use_in_Project": "Available readings are averaged"
    },
    {
        "Variable": "BPQ020",
        "Source_Dataset": "BPQ",
        "Category": "Blood pressure",
        "Description": "Ever told by a health professional that participant had high blood pressure",
        "Unit_or_Coding": "1 = Yes; 2 = No",
        "Research_Role": "Outcome component",
        "Use_in_Project": "Supports identification of hypertension"
    },
    {
        "Variable": "BPQ040A",
        "Source_Dataset": "BPQ",
        "Category": "Blood pressure",
        "Description": "Currently taking prescribed medicine for hypertension",
        "Unit_or_Coding": "1 = Yes; 2 = No",
        "Research_Role": "Outcome component",
        "Use_in_Project": "Identifies treated elevated blood pressure"
    },
    {
        "Variable": "LBXGLU",
        "Source_Dataset": "GLU",
        "Category": "Glycaemia",
        "Description": "Fasting plasma glucose",
        "Unit_or_Coding": "mg/dL",
        "Research_Role": "Outcome component",
        "Use_in_Project": "Abnormal when fasting glucose is at least 100 mg/dL"
    },
    {
        "Variable": "DIQ050",
        "Source_Dataset": "DIQ",
        "Category": "Glycaemia",
        "Description": "Currently taking insulin",
        "Unit_or_Coding": "1 = Yes; 2 = No",
        "Research_Role": "Outcome component",
        "Use_in_Project": "Identifies glucose-lowering treatment"
    },
    {
        "Variable": "DIQ070",
        "Source_Dataset": "DIQ",
        "Category": "Glycaemia",
        "Description": "Currently taking diabetic pills to lower blood sugar",
        "Unit_or_Coding": "1 = Yes; 2 = No",
        "Research_Role": "Outcome component",
        "Use_in_Project": "Identifies glucose-lowering treatment"
    },
    {
        "Variable": "LBXTR",
        "Source_Dataset": "TRIGLY",
        "Category": "Lipids",
        "Description": "Fasting triglyceride concentration",
        "Unit_or_Coding": "mg/dL",
        "Research_Role": "Outcome component",
        "Use_in_Project": "Abnormal when triglycerides are at least 150 mg/dL"
    },
    {
        "Variable": "LBDHDD",
        "Source_Dataset": "HDL",
        "Category": "Lipids",
        "Description": "Direct HDL cholesterol concentration",
        "Unit_or_Coding": "mg/dL",
        "Research_Role": "Outcome component",
        "Use_in_Project": "Abnormal below 40 for men or below 50 for women"
    },
    {
        "Variable": "WHtR",
        "Source_Dataset": "Derived",
        "Category": "Anthropometric index",
        "Description": "Waist-to-height ratio",
        "Unit_or_Coding": "BMXWAIST ÷ BMXHT",
        "Research_Role": "Derived predictor",
        "Use_in_Project": "Compared with BMI, BRI and ABSI"
    },
    {
        "Variable": "BRI",
        "Source_Dataset": "Derived",
        "Category": "Anthropometric index",
        "Description": "Body Roundness Index",
        "Unit_or_Coding": "Calculated from waist circumference and height",
        "Research_Role": "Derived predictor",
        "Use_in_Project": "Compared with BMI, WHtR and ABSI"
    },
    {
        "Variable": "ABSI",
        "Source_Dataset": "Derived",
        "Category": "Anthropometric index",
        "Description": "A Body Shape Index",
        "Unit_or_Coding": "Calculated from waist, BMI and height",
        "Research_Role": "Derived predictor",
        "Use_in_Project": "Compared with BMI, WHtR and BRI"
    },
    {
        "Variable": "Risk_Component_Count",
        "Source_Dataset": "Derived",
        "Category": "Clinical outcome",
        "Description": "Number of abnormal clinical components",
        "Unit_or_Coding": "Integer from 0 to 4",
        "Research_Role": "Outcome construction",
        "Use_in_Project": "Sum of blood pressure, glycaemia, triglyceride and HDL indicators"
    },
    {
        "Variable": "Elevated_Risk_Profile",
        "Source_Dataset": "Derived",
        "Category": "Clinical outcome",
        "Description": "Research-defined elevated cardiometabolic-risk profile",
        "Unit_or_Coding": "1 = At least 2 abnormalities; 0 = Fewer than 2",
        "Research_Role": "Dependent variable",
        "Use_in_Project": "Binary target predicted by the machine-learning models"
    }
]

research_dictionary = pd.DataFrame(research_variables)

display(research_dictionary)

,Variable,Source_Dataset,Category,Description,Unit_or_Coding,Research_Role,Use_in_Project
0,SEQN,All datasets,Identifier,Unique NHANES participant identification number,Participant ID,Merge key,Links records belonging to the same participant
1,RIDAGEYR,DEMO,Demographic,Participant age at screening,Years,Predictor,Adults aged 20–79; included in prediction models
2,RIAGENDR,DEMO,Demographic,Participant sex,1 = Male; 2 = Female,Predictor,Converted into a model-ready sex indicator
3,SDMVPSU,DEMO,Survey design,Masked primary sampling unit,NHANES survey-design code,Survey design,Used for survey-weighted variance estimation
4,SDMVSTRA,DEMO,Survey design,Masked variance stratum,NHANES survey-design code,Survey design,Used for survey-weighted variance estimation
5,WTSAF2YR,GLU / TRIGLY,Survey weight,Two-year fasting-subsample examination weight,Survey weight,Analysis weight,Required because fasting glucose and triglycer...
6,BMXHT,BMX,Anthropometric,Standing height,Centimetres,Input predictor,"Used to calculate WHtR, BRI and ABSI"
7,BMXWT,BMX,Anthropometric,Measured body weight,Kilograms,Supporting variable,Used for body-measurement checks
8,BMXWAIST,BMX,Anthropometric,Measured waist circumference,Centimetres,Input predictor,"Used to calculate WHtR, BRI and ABSI"
9,BMXBMI,BMX,Anthropometric,Body mass index,kg/m²,Predictor,BMI comparison model and normal-BMI subgroup
10,BPXSY1–BPXSY4,BPX,Blood pressure,Repeated systolic blood-pressure measurements,mmHg,Outcome component,Available readings are averaged
11,BPXDI1–BPXDI4,BPX,Blood pressure,Repeated diastolic blood-pressure measurements,mmHg,Outcome component,Available readings are averaged
12,BPQ020,BPQ,Blood pressure,Ever told by a health professional that partic...,1 = Yes; 2 = No,Outcome component,Supports identification of hypertension
13,BPQ040A,BPQ,Blood pressure,Currently taking prescribed medicine for hyper...,1 = Yes; 2 = No,Outcome component,Identifies treated elevated blood pressure
14,LBXGLU,GLU,Glycaemia,Fasting plasma glucose,mg/dL,Outcome component,Abnormal when fasting glucose is at least 100 ...
15,DIQ050,DIQ,Glycaemia,Currently taking insulin,1 = Yes; 2 = No,Outcome component,Identifies glucose-lowering treatment
16,DIQ070,DIQ,Glycaemia,Currently taking diabetic pills to lower blood...,1 = Yes; 2 = No,Outcome component,Identifies glucose-lowering treatment
17,LBXTR,TRIGLY,Lipids,Fasting triglyceride concentration,mg/dL,Outcome component,Abnormal when triglycerides are at least 150 m...
18,LBDHDD,HDL,Lipids,Direct HDL cholesterol concentration,mg/dL,Outcome component,Abnormal below 40 for men or below 50 for women
19,WHtR,Derived,Anthropometric index,Waist-to-height ratio,BMXWAIST ÷ BMXHT,Derived predictor,"Compared with BMI, BRI and ABSI"
20,BRI,Derived,Anthropometric index,Body Roundness Index,Calculated from waist circumference and height,Derived predictor,"Compared with BMI, WHtR and ABSI"
21,ABSI,Derived,Anthropometric index,A Body Shape Index,"Calculated from waist, BMI and height",Derived predictor,"Compared with BMI, WHtR and BRI"
22,Risk_Component_Count,Derived,Clinical outcome,Number of abnormal clinical components,Integer from 0 to 4,Outcome construction,"Sum of blood pressure, glycaemia, triglyceride..."
23,Elevated_Risk_Profile,Derived,Clinical outcome,Research-defined elevated cardiometabolic-risk...,1 = At least 2 abnormalities; 0 = Fewer than 2,Dependent variable,Binary target predicted by the machine-learnin...

In [12]:
dataset_register = pd.DataFrame([
    ["DEMO", "Demographics and survey design", "Age, sex, survey weights, strata and PSU", "Primary"],
    ["BMX", "Body measurements", "Height, weight, waist circumference and BMI", "Primary"],
    ["BPX", "Blood-pressure examination", "Repeated systolic and diastolic readings", "Primary"],
    ["BPQ", "Blood-pressure questionnaire", "Hypertension history and treatment", "Primary"],
    ["GLU", "Plasma fasting glucose", "Fasting glucose and fasting-subsample weight", "Primary"],
    ["DIQ", "Diabetes questionnaire", "Insulin and diabetic-pill use", "Primary"],
    ["TRIGLY", "Triglycerides", "Fasting triglyceride measurement", "Primary"],
    ["HDL", "HDL cholesterol", "Direct HDL cholesterol measurement", "Primary"],
    ["DR1TOT", "Dietary intake", "First-day total nutrient intake", "Secondary"],
    ["PAQ", "Physical activity", "Self-reported physical-activity information", "Secondary"]
], columns=[
    "Dataset",
    "Description",
    "Information_Used",
    "Analysis_Priority"
])

raw_column_inventory = []

print("Building technical column inventory")
print("=" * 70)

for number, xpt_path in enumerate(extracted_xpt_files, start=1):

    cycle = xpt_path.parent.name
    dataset_name = xpt_path.stem.upper()

    dataframe = pd.read_sas(
        xpt_path,
        format="xport",
        encoding="latin-1"
    )

    for column in dataframe.columns:

        non_missing = int(dataframe[column].notna().sum())
        missing = int(dataframe[column].isna().sum())
        unique_values = int(dataframe[column].nunique(dropna=True))

        examples = (
            dataframe[column]
            .dropna()
            .astype(str)
            .drop_duplicates()
            .head(3)
            .tolist()
        )

        raw_column_inventory.append({
            "Survey_Cycle": cycle,
            "Dataset": dataset_name,
            "Variable": column,
            "Data_Type": str(dataframe[column].dtype),
            "Total_Rows": len(dataframe),
            "Non_Missing": non_missing,
            "Missing": missing,
            "Missing_Percent": (
                missing / len(dataframe)
                if len(dataframe) > 0
                else None
            ),
            "Unique_Non_Missing": unique_values,
            "Example_Values": ", ".join(examples)
        })

    print(
        f"{number:02d}/30 | {cycle} | "
        f"{dataset_name} | {len(dataframe.columns)} variables"
    )

raw_columns_dictionary = pd.DataFrame(raw_column_inventory)

dictionary_folder = project_folder / "data_dictionary"
dictionary_folder.mkdir(parents=True, exist_ok=True)

dictionary_file = dictionary_folder / "NHANES_Data_Dictionary.xlsx"

with pd.ExcelWriter(dictionary_file, engine="openpyxl") as writer:

    research_dictionary.to_excel(
        writer,
        sheet_name="Research_Variables",
        index=False
    )

    dataset_register.to_excel(
        writer,
        sheet_name="Dataset_Register",
        index=False
    )

    raw_columns_dictionary.to_excel(
        writer,
        sheet_name="All_Raw_Columns",
        index=False
    )

    for worksheet in writer.book.worksheets:

        worksheet.freeze_panes = "A2"
        worksheet.auto_filter.ref = worksheet.dimensions

        for cell in worksheet[1]:
            cell.font = Font(bold=True, color="FFFFFF")
            cell.fill = PatternFill(
                fill_type="solid",
                fgColor="1F4E78"
            )
            cell.alignment = Alignment(
                horizontal="center",
                vertical="center",
                wrap_text=True
            )

        worksheet.row_dimensions[1].height = 30

        for column_cells in worksheet.columns:
            column_letter = column_cells[0].column_letter

            maximum_length = max(
                len(str(cell.value)) if cell.value is not None else 0
                for cell in list(column_cells)[:250]
            )

            worksheet.column_dimensions[column_letter].width = min(
                maximum_length + 2,
                45
            )

    # Percentage formatting in the raw-column inventory
    raw_sheet = writer.book["All_Raw_Columns"]

    for cell in raw_sheet["H"][1:]:
        cell.number_format = "0.0%"

print("\nDATA DICTIONARY CREATED")
print("-" * 70)
print("Workbook:", dictionary_file)
print("Research variables:", len(research_dictionary))
print("Dataset types:", len(dataset_register))
print("Raw-column records:", len(raw_columns_dictionary))
print("Status: Successfully saved to Google Drive.")

Building technical column inventory
======================================================================
01/30 | 2013_2014 | BMX_H | 26 variables
02/30 | 2013_2014 | BPQ_H | 14 variables
03/30 | 2013_2014 | BPX_H | 23 variables
04/30 | 2013_2014 | DEMO_H | 47 variables
05/30 | 2013_2014 | DIQ_H | 54 variables
06/30 | 2013_2014 | DR1TOT_H | 168 variables
07/30 | 2013_2014 | GLU_H | 6 variables
08/30 | 2013_2014 | HDL_H | 3 variables
09/30 | 2013_2014 | PAQ_H | 96 variables
10/30 | 2013_2014 | TRIGLY_H | 6 variables
11/30 | 2015_2016 | BMX_I | 26 variables
12/30 | 2015_2016 | BPQ_I | 11 variables
13/30 | 2015_2016 | BPX_I | 21 variables
14/30 | 2015_2016 | DEMO_I | 47 variables
15/30 | 2015_2016 | DIQ_I | 54 variables
16/30 | 2015_2016 | DR1TOT_I | 168 variables
17/30 | 2015_2016 | GLU_I | 4 variables
18/30 | 2015_2016 | HDL_I | 3 variables
19/30 | 2015_2016 | PAQ_I | 94 variables
20/30 | 2015_2016 | TRIGLY_I | 6 variables
21/30 | 2017_2018 | BMX_J | 21 variables
22/30 | 2017_2018 | BPQ_J | 11 variables
23/30 | 2017_2018 | BPX_J | 21 variables
24/30 | 2017_2018 | DEMO_J | 46 variables
25/30 | 2017_2018 | DIQ_J | 54 variables
26/30 | 2017_2018 | DR1TOT_J | 168 variables
27/30 | 2017_2018 | GLU_J | 4 variables
28/30 | 2017_2018 | HDL_J | 3 variables
29/30 | 2017_2018 | PAQ_J | 17 variables
30/30 | 2017_2018 | TRIGLY_J | 10 variables

DATA DICTIONARY CREATED
----------------------------------------------------------------------
Workbook: /content/drive/MyDrive/NHANES_Project/data_dictionary/NHANES_Data_Dictionary.xlsx
Research variables: 24
Dataset types: 10
Raw-column records: 1232
Status: Successfully saved to Google Drive.

In [13]:
excel_files = sorted(excel_root.rglob("*.xlsx"))

print("FINAL EXTRACTION AUDIT")
print("-" * 60)
print("Excel datasets created:", len(excel_files))
print("Extraction summary exists:", summary_file.exists())
print("Data dictionary exists:", dictionary_file.exists())

for cycle in ["2013_2014", "2015_2016", "2017_2018"]:
    cycle_count = len(list((excel_root / cycle).glob("*.xlsx")))
    print(f"{cycle}: {cycle_count} Excel files")

if (
    len(excel_files) == 30
    and summary_file.exists()
    and dictionary_file.exists()
):
    print("\nStatus: DATA EXTRACTION COMPLETED SUCCESSFULLY")
else:
    print("\nStatus: Check the missing outputs before continuing")

FINAL EXTRACTION AUDIT
------------------------------------------------------------
Excel datasets created: 30
Extraction summary exists: True
Data dictionary exists: True
2013_2014: 10 Excel files
2015_2016: 10 Excel files
2017_2018: 10 Excel files

Status: DATA EXTRACTION COMPLETED SUCCESSFULLY